dist: trusty
sudo: false

language: node_js
node_js:
- "12"

addons:
  chrome: stable

cache:
  directories:
  - ./node_modules

before_install:
  - LATEST_CHROMEDRIVER_VERSION=`curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE`
  - curl https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip -O
  - unzip chromedriver_linux64.zip -d ~/bin

install:
  - npm install

script:
- npm run packagr
- ng test --watch=false --progress=false --browsers=ChromeHeadlessCI
- ng e2e --protractor-config=./protractor-ci.conf.js
